apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ randAlphaNum 50 | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.backend.database.password | b64enc | quote }}
